"""
github_automation.py -- Full Git/GitHub automation for JARVIS.

Supports: init, scaffold, status, add, commit, push, pull, log,
          branch, checkout, diff, clone, reset, stash, remote_add
"""

import os
import subprocess
import sys
from pathlib import Path

# Ensure stdout handles unicode on Windows
try:
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except Exception:
    pass

# ── Helpers ──────────────────────────────────────────────────────────────────

def _run(args: list[str], cwd: str | None = None,
         timeout: int = 30) -> tuple[int, str, str]:
    """Run a git command, return (returncode, stdout, stderr)."""
    try:
        result = subprocess.run(
            args,
            cwd=cwd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
        )
        return result.returncode, result.stdout.strip(), result.stderr.strip()
    except FileNotFoundError:
        return -1, "", "git is not installed or not on PATH."
    except subprocess.TimeoutExpired:
        return -1, "", f"Command timed out after {timeout}s."
    except Exception as e:
        return -1, "", str(e)


def _ok(msg: str, player=None) -> str:
    print(f"[GitHub] OK {msg}")
    if player:
        try:
            player.write_log(f"GIT: {msg}")
        except Exception:
            pass
    return msg


def _err(msg: str, player=None) -> str:
    print(f"[GitHub] ERR {msg}")
    if player:
        try:
            player.write_log(f"GIT ERR: {msg}")
        except Exception:
            pass
    return f"Error: {msg}"


def _resolve(path: str) -> str:
    """Expand ~ and make absolute."""
    return str(Path(path).expanduser().resolve())


# ── Actions ───────────────────────────────────────────────────────────────────

def _init(path: str, player=None) -> str:
    path = _resolve(path)
    os.makedirs(path, exist_ok=True)
    rc, out, err = _run(["git", "init"], cwd=path)
    if rc != 0:
        return _err(err or "git init failed", player)
    return _ok(f"Git repository initialized at {path}", player)


def _scaffold(path: str, player=None) -> str:
    path = _resolve(path)
    os.makedirs(path, exist_ok=True)
    created = []

    gitignore = Path(path) / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(
            "# .gitignore — generated by JARVIS\n"
            "__pycache__/\n*.py[cod]\n*.pyo\n.env\n.venv/\nvenv/\n"
            "*.log\n*.tmp\n.DS_Store\nnode_modules/\ndist/\nbuild/\n"
            "*.egg-info/\n.idea/\n.vscode/settings.json\n",
            encoding="utf-8",
        )
        created.append(".gitignore")

    readme = Path(path) / "README.md"
    if not readme.exists():
        project_name = Path(path).name
        readme.write_text(
            f"# {project_name}\n\n"
            "> Created with JARVIS\n\n"
            "## Getting Started\n\n"
            "```bash\n# Install dependencies\npip install -r requirements.txt\n\n"
            "# Run the project\npython main.py\n```\n\n"
            "## License\n\nMIT\n",
            encoding="utf-8",
        )
        created.append("README.md")

    if created:
        return _ok(f"Scaffolded {', '.join(created)} at {path}", player)
    return _ok(f"Files already exist at {path} — nothing to scaffold.", player)


def _status(path: str, player=None) -> str:
    path = _resolve(path)
    if not (Path(path) / ".git").exists():
        return _err(f"Not a git repository: {path}", player)
    rc, out, err = _run(["git", "status", "--short", "--branch"], cwd=path)
    if rc != 0:
        return _err(err or "git status failed", player)
    return _ok(out or "Working tree clean.", player)


def _add(path: str, files: str = ".", player=None) -> str:
    path = _resolve(path)
    target = files.strip() or "."
    rc, out, err = _run(["git", "add", target], cwd=path)
    if rc != 0:
        return _err(err or "git add failed", player)
    return _ok(f"Staged: {target}", player)


def _commit(path: str, message: str, player=None) -> str:
    path = _resolve(path)
    if not message:
        return _err("Commit message is required.", player)
    rc, out, err = _run(["git", "commit", "-m", message], cwd=path)
    if rc != 0:
        # Check for "nothing to commit"
        if "nothing to commit" in err.lower() or "nothing to commit" in out.lower():
            return _ok("Nothing to commit — working tree is clean.", player)
        return _err(err or out or "git commit failed", player)
    return _ok(out.splitlines()[0] if out else "Committed.", player)


def _push(path: str, remote: str = "origin",
          branch: str = "", player=None) -> str:
    path = _resolve(path)
    cmd = ["git", "push", remote]
    if branch:
        cmd.append(branch)
    rc, out, err = _run(cmd, cwd=path, timeout=60)
    if rc != 0:
        return _err(err or "git push failed", player)
    return _ok(out or err or "Push complete.", player)


def _pull(path: str, remote: str = "origin",
          branch: str = "", player=None) -> str:
    path = _resolve(path)
    cmd = ["git", "pull", remote]
    if branch:
        cmd.append(branch)
    rc, out, err = _run(cmd, cwd=path, timeout=60)
    if rc != 0:
        return _err(err or "git pull failed", player)
    return _ok(out or "Pull complete.", player)


def _log(path: str, count: int = 10, player=None) -> str:
    path = _resolve(path)
    rc, out, err = _run(
        ["git", "log", f"--max-count={count}",
         "--oneline", "--decorate"],
        cwd=path,
    )
    if rc != 0:
        return _err(err or "git log failed", player)
    if not out:
        return _ok("No commits yet.", player)
    return _ok(f"Last {count} commits:\n{out}", player)


def _branch(path: str, name: str = "", player=None) -> str:
    path = _resolve(path)
    if name:
        rc, out, err = _run(["git", "branch", name], cwd=path)
        if rc != 0:
            return _err(err or "Could not create branch", player)
        return _ok(f"Branch '{name}' created.", player)
    # List branches
    rc, out, err = _run(["git", "branch", "-a"], cwd=path)
    if rc != 0:
        return _err(err or "Could not list branches", player)
    return _ok(out or "No branches found.", player)


def _checkout(path: str, branch: str, create: bool = False,
              player=None) -> str:
    path = _resolve(path)
    if not branch:
        return _err("Branch name is required.", player)
    cmd = ["git", "checkout"]
    if create:
        cmd += ["-b", branch]
    else:
        cmd.append(branch)
    rc, out, err = _run(cmd, cwd=path)
    if rc != 0:
        return _err(err or "Checkout failed", player)
    return _ok(f"Switched to {'new ' if create else ''}branch '{branch}'.", player)


def _diff(path: str, staged: bool = False, player=None) -> str:
    path = _resolve(path)
    cmd = ["git", "diff"]
    if staged:
        cmd.append("--staged")
    rc, out, err = _run(cmd, cwd=path)
    if rc != 0:
        return _err(err or "git diff failed", player)
    if not out:
        return _ok("No differences found.", player)
    # Truncate very long diffs
    truncated = out[:4000]
    if len(out) > 4000:
        truncated += f"\n... [{len(out) - 4000} more chars truncated]"
    return _ok(truncated, player)


def _clone(url: str, destination: str = "", player=None) -> str:
    if not url:
        return _err("Repository URL is required.", player)
    cmd = ["git", "clone", url]
    if destination:
        cmd.append(_resolve(destination))
    rc, out, err = _run(cmd, timeout=120)
    if rc != 0:
        return _err(err or "git clone failed", player)
    return _ok(out or err or f"Cloned {url}", player)


def _reset(path: str, mode: str = "mixed",
           ref: str = "HEAD", player=None) -> str:
    path = _resolve(path)
    allowed = {"soft", "mixed", "hard"}
    if mode not in allowed:
        return _err(f"Mode must be one of: {', '.join(allowed)}", player)
    rc, out, err = _run(["git", "reset", f"--{mode}", ref], cwd=path)
    if rc != 0:
        return _err(err or "git reset failed", player)
    return _ok(f"Reset ({mode}) to {ref}.", player)


def _stash(path: str, action: str = "push",
           message: str = "", player=None) -> str:
    path = _resolve(path)
    cmd = ["git", "stash"]
    if action == "push":
        if message:
            cmd += ["push", "-m", message]
        else:
            cmd.append("push")
    elif action == "pop":
        cmd.append("pop")
    elif action == "list":
        cmd.append("list")
    elif action == "drop":
        cmd.append("drop")
    else:
        return _err(f"Unknown stash action: {action}. Use push|pop|list|drop", player)
    rc, out, err = _run(cmd, cwd=path)
    if rc != 0:
        return _err(err or f"git stash {action} failed", player)
    return _ok(out or f"Stash {action} complete.", player)


def _remote_add(path: str, name: str, url: str, player=None) -> str:
    path = _resolve(path)
    if not name or not url:
        return _err("Remote name and URL are required.", player)
    rc, out, err = _run(["git", "remote", "add", name, url], cwd=path)
    if rc != 0:
        return _err(err or "Could not add remote", player)
    return _ok(f"Remote '{name}' → {url} added.", player)


# ── Entry Point ───────────────────────────────────────────────────────────────

def github_automation(
    parameters: dict = None,
    response=None,
    player=None,
    session_memory=None,
) -> str:
    """
    JARVIS Git/GitHub automation tool.

    parameters:
        action  : init | scaffold | status | add | commit | push | pull |
                  log | branch | checkout | diff | clone | reset | stash |
                  remote_add
        path    : local repository path (default: '.')
        message : commit message
        files   : files to stage (default: '.')
        remote  : remote name (default: 'origin')
        branch  : branch name for branch/checkout/push/pull
        url     : remote URL for clone/remote_add
        name    : branch name (for branch) or remote name (for remote_add)
        count   : number of log entries (default: 10)
        create  : bool — create new branch on checkout
        staged  : bool — diff staged files
        mode    : reset mode: soft|mixed|hard
        ref     : git ref for reset (default: HEAD)
        stash_action : push|pop|list|drop
    """
    p = parameters or {}
    action = p.get("action", "").strip().lower()
    path   = p.get("path", ".").strip()

    if not action:
        return _err("No action specified. Use init, scaffold, status, add, commit, push, pull, log, branch, checkout, diff, clone, reset, stash, or remote_add.", player)

    print(f"[GitHub] action={action}  path={path}")

    if action == "init":
        return _init(path, player)

    elif action == "scaffold":
        return _scaffold(path, player)

    elif action == "status":
        return _status(path, player)

    elif action == "add":
        return _add(path, files=p.get("files", "."), player=player)

    elif action == "commit":
        return _commit(path, message=p.get("message", ""), player=player)

    elif action == "push":
        return _push(path,
                     remote=p.get("remote", "origin"),
                     branch=p.get("branch", ""),
                     player=player)

    elif action == "pull":
        return _pull(path,
                     remote=p.get("remote", "origin"),
                     branch=p.get("branch", ""),
                     player=player)

    elif action == "log":
        return _log(path, count=int(p.get("count", 10)), player=player)

    elif action == "branch":
        return _branch(path, name=p.get("name", ""), player=player)

    elif action == "checkout":
        return _checkout(path,
                         branch=p.get("branch", p.get("name", "")),
                         create=bool(p.get("create", False)),
                         player=player)

    elif action == "diff":
        return _diff(path, staged=bool(p.get("staged", False)), player=player)

    elif action == "clone":
        return _clone(p.get("url", ""), destination=path, player=player)

    elif action == "reset":
        return _reset(path,
                      mode=p.get("mode", "mixed"),
                      ref=p.get("ref", "HEAD"),
                      player=player)

    elif action == "stash":
        return _stash(path,
                      action=p.get("stash_action", "push"),
                      message=p.get("message", ""),
                      player=player)

    elif action == "remote_add":
        return _remote_add(path,
                           name=p.get("name", "origin"),
                           url=p.get("url", ""),
                           player=player)

    else:
        return _err(
            f"Unknown action: '{action}'. "
            "Use: init | scaffold | status | add | commit | push | pull | "
            "log | branch | checkout | diff | clone | reset | stash | remote_add",
            player,
        )
